const products = [
    {
        id: "1",
        img: "/Images/blog/PressRelease.jpg",
        blogImg: "/Images/blog/productBlog/digital-solution-provider.jpg",
        data: "\n\nOrion has been named as the winners of the Best Digital Solution Providers at the Green Shipping Summit 2019, honouring the best in class Digital operation & Development initiatives within the maritime industry.\n\n The company was recognised for its services and initiatives that demonstrate a commitment to advancing and improving digital operations in maritime sector, ensuring efficiency and safety that exemplifies technological advancement in the new age dawn of maritime explorations and acts as a significant pacifier in the cause of maritime regulations and reforms.\n\n “Orion is extremely Proud and humbled by this honour, we hope our solutions can contribute to strategic business benefits that are to be reaped by ship owners and managers, from operational efficiency improvements and cost reductions to environmental performance enhancements” said Capt. Mohit Sabharwal; Founder Orion Marine Concepts.\n\n Winners will be honoured at the 3rd Green Maritime Forum in Hamburg in March 2020 where Wisdom events will be hosting their annual awards for Maritime.\n\n",
        dataHead: "WINNER OF THE BEST DIGITAL SOLUTION PROVIDERS",
        dataDate: "10:45h in News by admin"
    },
    {
        id: "2",
        img: "/Images/blog/SpeechAnalyticsBLOG.png",
        blogImg: "/Images/blog/productBlog/daniel.jpg",
        data: "\n\nIndian maritime software services provider Orion Marine Concepts has launched a new voice-activated intelligent assistant called Daniel.\n\n Users in the maritime industry can use the latest technology to leverage voice commands for obtaining relevant and precise document information.\n\n According to Orion Marine, the introduction of the new assistant is a significant innovation in the maritime industry given the current fluency level of shipping.\n\n Orion Marine has already activated and launched Daniel on its Document Management System and made it available for existing clients.\n\n The additional AI block in the pre-existing system has made the functionality easy as the software interacts with its efficient search method.\n\n Daniel also offers other useful industry links and guidelines that help users to discover desired and relevant information.\n\n “The market size of the global Speech and Voice Recognition is estimated to reach $31.82bn by 2025.”\n\n In May 2017, Orion Marine launched the pool point performance monitoring section on the NAU version 2.0 designed to monitor the performance of the vessels operating within a pool.\n\n Performance is measured daily against a standard pool ship’s fuel and speed parameters.\n\n Orion Marine has been creating bespoke software for the maritime industry since 2006 and provides software services to more than 300 vessels.\n\n",
        dataHead: "ORION MARINE LAUNCHES DANIEL VOICE-ACTIVATED ASSISTANT",
        dataDate: "11:23h in News by admin"
    },
    {
        id: "3",
        img: "/Images/blog/App.png",
        blogImg: "/Images/blog/productBlog/app-release.jpg",
        data: "\n\nIndia-based Orion Marine Concepts has launched a fleet management application, NAU Fleet Performance, to improve efficiency, lower operational costs and cut emissions.\n\n The NAU app provides information on each aspect of operation and activity of a vessel’s voyage. It provides a complete operational overview through performance KPIs, such as consumption, speed, charter party compliance, weather and next port information with ETA, decision support, voyage tracking, inventory overview, energy efficiency operating, calculation of CO2, nitrogen oxides (NOx) and sulfur oxides (SOx).\n\n The NAU Fleet Performance app benefits from a user-friendly user interface that is not interactive and helps the user to control the\n\n Capt. Mohit Sabharwal, director, technical and operations, said: “The operator receives invaluable information on every operation and activity on the APP based on the acquired measurements, a set of performance parameters which are calculated continuously and available for the fleet to the users to manage their vessels in a more economical and environmentally beneficial way.”\n\n",
        dataHead: "ORION MARINE CONCEPTS LAUNCHES FLEET MANAGEMENT APP",
        dataDate: "11:15h in News by admin"
    },
    {
        id: "4",
        img: "/Images/blog/ShipDeck.png",
        blogImg: "/Images/blog/productBlog/customize-software.jpg",
        data: "\n\nsoftware product planning is critical to the development of a Software Product. We, at Orion Marine Concepts, help our customers by converting their product vision into a successful product. Our experts offer an entire spectrum of activities that start from the conceptualization of a product and end when the product is finally shipped to our customers.\n\n We are ideally manned to manage the three variables of product development- time, resources, and scope effectively and efficiently. This is the reason why we can guarantee a successful product release, offering you peace of mind.\n\n Our proficient and qualified experts have developed components, methodologies, and frameworks to ensure top-notch quality and efficient performance. For every area of development, we bring a specific methodology.\n\n Our product development cycle features the following steps:\n\n Architecture Design and Development Product Reengineering SaaS Enablement Product Deployment Support Embedded Software and Hardware Design & Development\n\n To ensure that all our above-mentioned sites run on a smooth track, our experts undertake the following:\n\n Market researchGathering requirements for the proposed business solution\n\n Devising a plan or design for the software-based solution\n\n Implementation of the software\n\n Testing the software\n\n Deployment\n\n Maintenance and bug fixing.\n\n",
        dataHead: "CUSTOMIZED SOFTWARE APPLICATIONS",
        dataDate: "10:53h in News by admin"
    },
    {
        id: "5",
        img: "/Images/blog/Picture1.jpg",
        blogImg: "/Images/blog/productBlog/green-summit.jpg",
        data: "\n\n Orion, the maritime digital solution Providers, announced it will be attending the 2019 International Green & Smart Shipping Summit, held at Mainport by Inntel Hotels, Rotterdam from 8th October- 9th October.\n\n Orion will be showcasing some new products, that focus on AI (Artificial Intelligence) and Voice Recognition Technology. Besides this, their green shipping software Suite will also be featured that includes Fleet Performance Energy Efficiency Mobile application, Marpol Seal logbook, E- Document Management, Waste Management System, etc. These products promote high standards of sustainability and profitability that include environmental & social responsibility.\n\n “Our Attendance at green summit underscores our dedication to helping marine industry reshape their strategies and best practices to adapt to the dramatically changing marine Sector”, said Capt. Mohit Sabharwal, Technical Director, and Founder.\n\n The 4th International Green & Smart Shipping Summit gained popularity among the maritime industry in the previous three years and is back to provide industry professionals with ways to reduce pollution from Shipping.\n\n Maritime experts and policymakers will delve into debates on alternative fuels, green port initiatives and the importance of digitalization for efficient & environmentally conscious ship operations. The event will also welcome influential decision-makers from key companies in the sector to help them learn new approaches to sustainability and ­partners during networking activities.\n\n With a conference, exhibition and networking opportunities – this Summit is a perfect recipe for success to any maritime business.\n\n Orion Marine Concepts comes with a futuristic approach for the current marine industry Landscape with its best-in-class and System integrated ERP suite.\n\n Our ERP solutions are well beyond just software systems. Our class approved systems are well-tailored to match the ever-changing needs of our customers. With a Product implementation team ensures the smooth transaction at every step, Orion guarantees stable communication and data management between the main office and the vessels.\n\n We offer a variety of software solution with broad functionality in procurement, maintenance, QHSSE, dry-docking, document management, inspections, Fleet Performance, etc. Our systems can be used as a single well-integrated ERP Solution or as separate systems catering to the specific needs of any organization.\n\n",
        dataHead: "ORION-MARINE-CONCEPTS-ANNOUNCES-ITS-PARTICIPATION-IN-THE-4TH-INTERNATIONAL-GREEN-SMART-SHIPPING-SUMMIT",
        dataDate: "08:46h in News by admin"
    },
    {
        id: "6",
        img: "/Images/blog/UaccOrion.jpg",
        blogImg: "/Images/blog/productBlog/software-performance.jpg",
        data: "\n\nOrion Marine Concepts, the maritime industry software provider since past decade, announces the launch of pool point performance monitoring section on the NAU version 2.0, this section is designed to monitor performance of the vessels which are operating within a pool. The performance is measured every day against a standard pool ship’s fuel and speed parameters. The section of the NAU provides a Comprehensive view of the speed and fuel quality performance and alerts users of the vessel’s performance deviation. This is created with high flexibility and easy scaling to any size of fleet and to cover mixed fleets.\n\n The ships reported data is continuously benchmarked with the standard data and presents tailor made rolling analytics with the Fleet KPIs for the speed and fuel efficiency measured with the dynamic averages for the bunker costs and daily hire rates. The dashboards and analytics of collected data and own reporting schemes can be shared with different departments and stakeholders as desired. The section has been created with the aim of demonstrating transparency and control for customers and other stakeholders and ready view of the real-time vessel performance.\n\n The management can at a glance identify best and worst performers to prioritize and evaluate improvement measures based on data, analytics and best practice. The data and the reports are created without any extra reports from the vessels or shore which ensures no extra efforts for pool point analysis.\n\n",
        dataHead: "ORION MARINE CONCEPTS ANNOUNCES THE ADDITION OF THE POOL POINTS PERFORMANCE SECTION IN THE NAU VER. 2.0",
        dataDate: "04:44h in News by admin"
    },
    {
        id: "7",
        img: "/Images/blog/Announcement.jpg",
        blogImg: "/Images/blog/productBlog/eu-mrv.jpg",
        data: "\n\n Orion Marine Concepts, creators of the maritime software, announce the NAU ver. 2.0 with classification type approved and confirming with the EU MRV requirements for monitoring and reporting of the emissions as per Annex II of the draft template document – EU Ref. Ares (2016) 3985800 – 28/07/2016. The NAU ver. 2.0 has been functional since a decade to collect large data and produce numerous fleet performance and emission reports.\n\n The system has been type approved for emissions monitoring and reporting requirements for the European Union in compliance with the EU 2015/757 and amending directive 2009/16/EC and is capable of automatically submitting the year end reports to the verifiers. The system can automatically generate both voyage reports and annual reports for individual ships – taking into consideration the location of the ports of call, and the cargo activity at these ports of call throughout the year as per the EU directive.\n\n The NAU ver. 2.0 is a robust and pragmatic system with high quality of reports automatically generated by the system. The system operates with the principle of genuinely supporting shipping companies in monitoring their performance and complying with the regulation by providing transparent and accurate data. The process and functionality of the NAU has been assessed numerous times by various Industry experts, which provide the leading edge to the system and its capabilities.\n\n",
        dataHead: "ORION MARINE CONCEPTS NAU VER. 2.0 TYPE APPROVED AND EU MRV READY FOR MONITORING",
        dataDate: "04:37h in News by admin"
    },
    {
        id: "8",
        img: "/Images/blog/UaccOrion.jpg",
        blogImg: "/Images/blog/productBlog/software-install.jpg",
        data: "\n\n United Arab Chemical Carriers (UACC) is installing fleet performance and monitoring software developed by India-based Orion Marine Concepts.\n\n The deal includes the rollout of Version 2.0 of the fleet management software suite on UACC’s fleet of 25 vessels and the office. It was due to be installed by the first week of January this year.\n\n Reliable on-board data collection, decision support for the crew, reporting to the officers and ship-to-shore data communications are key features of the software, Orion said.\n\n The new Version 2.0 of fleet monitoring includes the evaluation and comparison of voyage KPIs, such as speed and distance travelled, fuel consumption (total and tonnes per day), fuel tonne per mile performance, etc.\n\n In addition, the system can also give voyage, propulsion & machinery optimisation, tracking & evaluation, fuel consumption and emissions plus data & Analytics, etc. The system complies with EU & IMO’s monitoring, reporting and verification (MRV) regulations for emissions control.\n\n ",
        dataHead: "UACC INSTALLS ORION SOFTWARE",
        dataDate: "10:04h in News by admin"
    },
    {
        id: "9",
        img: "/Images/blog/Announcement.jpg",
        blogImg: "/Images/blog/productBlog/o-invent.jpg",
        data: "\n\n Orion Credence Solutions, India, Pioneers in Marine Software have released their novelty product “O– Invent”. “O-Invent is a distinguished inventory management device. It features a barcode scanner along with a section to manage the inventory. The application is designed to work with Orion Enterprise or any inventory management suite which can provide the inventory output in an excel format.\n\n This device can import from excel and then allows users to work and reverse synchronize to the inventory master database through its own excel output.” The users can create barcodes for the new items, print and attach them to the items. It uses the device camera to scan the barcodes, lookup the item within the database, and points to the inventory item for users to update the reserve on-board quantity (ROB).\n\n Below are few features of “O-Invent”:\n\n – Inventory Management & Control:\n\n To work on both the spares and stores on board the vessels. Barcodes can be assigned to each item in line with companies existing item codes, parent groups, locations etc.\n\n – Mobility and Identification:\n\n The mobile device allows the user to view and update the inventory by their groups and/or store locations. The items can be identified simply by scanning the bar code stickers to update their ROB.\n\n – Preferences:\n\n The inventory files can be viewed and searched by the defined filters, such as; by items, by groups, text search, numeric search, etc.\n\n – Device Communication:\n\n Based on the receiving PC capability, this device can communicate through USB port or WIFI.\n\n Orion embraces “All Aspects of Shipping, equipped with complete maritime suite.” Founded in 2006, from modest beginnings, Orion Marine Concepts has grown to be a professionally managed project management and shipping software solutions provider with a multinational client base with a complete ERP suite for marine industry. Our dedicated team is well versed about maritime software requirements and always strive their best in development, ployment and support of Solution that ease and time for both ship and shore staff respectively. Orion is headed by a team of Master Mariners, Marine Engineers and IT Professionals.\n\n In addition our people have a well-rounded exposure to the requirements of the international maritime trade. The scope of our services spans new building project management, ship/shore services, software design, development and analysis, marine engineering, techno commercial feasibility, port and shipyard development and marine cargo services.\n\n ",
        dataHead: "ORION CREDENCE SOLUTIONS LAUNCHES O-INVENT",
        dataDate: "12:44h in News by admin"
    },
    {
        id: "10",
        img: "/Images/blog/QstrataNews.jpg",
        blogImg: "/Images/blog/productBlog/saas-suite.jpg",
        data: "\n\n Orion Marine Concepts, India, Pioneers in Maritime based Software have released a Strategic Intelligence software suite approved by DNV – GL.\n\n With the aim for achieving excellence, Orion Marine along with Chembulk Tankers, USA has taken the lead in developing this State of the Art Quality Assurance & Fleet Performance Management suite, named Q – Strata.\n\n Q – Strata is a comprehensive web-based tool for efficient management of Quality Health & Safety and Environmental aspects of the fleet operations.\n\n Correctly utilized, the information resources will enable quick analysis of the information with regards to the operational & management health of the organisation.\n\n As Capt. Ahmed Raza Khan of the Chembulk Tankers, says; “Q – Strata will provide niche control over our Ship Managing Partners and allow us to grow our strengths in magnitudes towards better and safer tomorrow for the Organization.”\n\n Main Features of the Q – Strata all under one platform are:\n\n Multiple Dashboards & Summaries,\n\n Bespoke Business Analytics,\n\n Performance Monitoring & Benchmarking,\n\n Incident Reporting & Management.\n\n Vetting Inspection Management & Fleet Status,\n\n Port State Control\n\n Inspections,\n\n Fleet OPEX Performance,\n\n Dry Dock planning and Budgets,\n\n Superintendent Inspections,\n\n Document Management,\n\n Custom made Filters and drill downs to the first Layer,\n\n Reports, Alerts, Highlights, Tracking & Notifications.\n\n About Orion\n\n Orion marine concepts embraces “All Aspects of Shipping, equipped with complete maritime suite.” Founded in 2006.From modest beginnings, Orion Marine Concepts has grown to be a professionally managed project management and shipping software solutions provider with a multinational client base with a complete ERP suite for marine industry. Leading Anti Drone Jammer Manufacturer since 2015!\n\n Our dedicated team is well versed about maritime software requirements and always strive their best in development, deployment and support of Solution that ease and time for both ship and shore staff respectively.\n\n Orion Marine Concepts is headed by a team of Master Mariners, Marine Engineers and IT Professionals. In addition our people have a well-rounded exposure to the requirements of the international maritime trade. The scope of our services spans new building project management, ship/shore services, software design, development and analysis, marine engineering, techno commercial feasibility, port and shipyard development and marine cargo services.",
        dataHead: "ORION MARINE CONCEPTS LAUNCHES Q-STRATA - A STRATEGIC INTELLIGENCE SOFTWARE SUITE!",
        dataDate: "12:00h in News by admin"
    },

]

export default products